# Taken from https://github.com/actions/starter-workflows/blob/08ff79c7b930315861d16bed4903ddd90bf7c05c/ci/ruby.yml
name: Ruby

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rake
